{{- if and .Values.rbac.create (not .Values.rbac.cluster) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "dask_kubernetes_operator.serviceAccountName" . }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "dask_kubernetes_operator.serviceAccountName" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "dask_kubernetes_operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
