// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	v1 "github.com/dask/dask-kubernetes/v2024/dask_kubernetes/operator/go_client/pkg/apis/kubernetes.dask.org/v1"
)

// DaskClusterStatusApplyConfiguration represents an declarative configuration of the DaskClusterStatus type for use
// with apply.
type DaskClusterStatusApplyConfiguration struct {
	Phase *v1.DaskClusterPhase `json:"phase,omitempty"`
}

// DaskClusterStatusApplyConfiguration constructs an declarative configuration of the DaskClusterStatus type for use with
// apply.
func DaskClusterStatus() *DaskClusterStatusApplyConfiguration {
	return &DaskClusterStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *DaskClusterStatusApplyConfiguration) WithPhase(value v1.DaskClusterPhase) *DaskClusterStatusApplyConfiguration {
	b.Phase = &value
	return b
}
