// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// DaskAutoscalerSpecApplyConfiguration represents an declarative configuration of the DaskAutoscalerSpec type for use
// with apply.
type DaskAutoscalerSpecApplyConfiguration struct {
	Cluster *string `json:"cluster,omitempty"`
	Minimum *string `json:"minimum,omitempty"`
	Maximum *string `json:"maximum,omitempty"`
}

// DaskAutoscalerSpecApplyConfiguration constructs an declarative configuration of the DaskAutoscalerSpec type for use with
// apply.
func DaskAutoscalerSpec() *DaskAutoscalerSpecApplyConfiguration {
	return &DaskAutoscalerSpecApplyConfiguration{}
}

// WithCluster sets the Cluster field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cluster field is set to the value of the last call.
func (b *DaskAutoscalerSpecApplyConfiguration) WithCluster(value string) *DaskAutoscalerSpecApplyConfiguration {
	b.Cluster = &value
	return b
}

// WithMinimum sets the Minimum field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Minimum field is set to the value of the last call.
func (b *DaskAutoscalerSpecApplyConfiguration) WithMinimum(value string) *DaskAutoscalerSpecApplyConfiguration {
	b.Minimum = &value
	return b
}

// WithMaximum sets the Maximum field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Maximum field is set to the value of the last call.
func (b *DaskAutoscalerSpecApplyConfiguration) WithMaximum(value string) *DaskAutoscalerSpecApplyConfiguration {
	b.Maximum = &value
	return b
}
