// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// DaskWorkerGroupSpecApplyConfiguration represents an declarative configuration of the DaskWorkerGroupSpec type for use
// with apply.
type DaskWorkerGroupSpecApplyConfiguration struct {
	Cluster *string                       `json:"cluster,omitempty"`
	Worker  *WorkerSpecApplyConfiguration `json:"worker,omitempty"`
}

// DaskWorkerGroupSpecApplyConfiguration constructs an declarative configuration of the DaskWorkerGroupSpec type for use with
// apply.
func DaskWorkerGroupSpec() *DaskWorkerGroupSpecApplyConfiguration {
	return &DaskWorkerGroupSpecApplyConfiguration{}
}

// WithCluster sets the Cluster field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cluster field is set to the value of the last call.
func (b *DaskWorkerGroupSpecApplyConfiguration) WithCluster(value string) *DaskWorkerGroupSpecApplyConfiguration {
	b.Cluster = &value
	return b
}

// WithWorker sets the Worker field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Worker field is set to the value of the last call.
func (b *DaskWorkerGroupSpecApplyConfiguration) WithWorker(value *WorkerSpecApplyConfiguration) *DaskWorkerGroupSpecApplyConfiguration {
	b.Worker = value
	return b
}
