// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// DaskJobSpecApplyConfiguration represents an declarative configuration of the DaskJobSpec type for use
// with apply.
type DaskJobSpecApplyConfiguration struct {
	Job     *JobSpecApplyConfiguration     `json:"job,omitempty"`
	Cluster *DaskClusterApplyConfiguration `json:"cluster,omitempty"`
}

// DaskJobSpecApplyConfiguration constructs an declarative configuration of the DaskJobSpec type for use with
// apply.
func DaskJobSpec() *DaskJobSpecApplyConfiguration {
	return &DaskJobSpecApplyConfiguration{}
}

// WithJob sets the Job field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Job field is set to the value of the last call.
func (b *DaskJobSpecApplyConfiguration) WithJob(value *JobSpecApplyConfiguration) *DaskJobSpecApplyConfiguration {
	b.Job = value
	return b
}

// WithCluster sets the Cluster field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cluster field is set to the value of the last call.
func (b *DaskJobSpecApplyConfiguration) WithCluster(value *DaskClusterApplyConfiguration) *DaskJobSpecApplyConfiguration {
	b.Cluster = value
	return b
}
