apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: daskjobs.kubernetes.dask.org
spec:
  scope: Namespaced
  group: kubernetes.dask.org
  names:
    kind: DaskJob
    plural: daskjobs
    singular: daskjob
    shortNames:
      - djb
  versions:
    - name: v1
      served: true
      storage: true
      additionalPrinterColumns:
        - name: Status
          type: string
          jsonPath: .status.jobStatus
        - name: Number Of Workers
          type: integer
          jsonPath: .spec.cluster.spec.worker.replicas
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              properties:
                clusterName:
                  type: string
                endTime:
                  type: string
                  format: date-time
                  nullable: true
                jobRunnerPodName:
                  type: string
                  nullable: true
                jobStatus:
                  type: string
                  nullable: true
                startTime:
                  type: string
                  format: date-time
                  nullable: true
              required:
                - jobStatus
              type: object
            spec:
              type: object
              required:
              - cluster
              - job
              properties:
                job:
                  type: object
                  properties:
                    metadata:
                      $ref: 'python://dask_kubernetes/operator/customresources/templates.yaml#/definitions/dask.k8s.api.v1.SimpleObjectMeta'
                    spec:
                      $ref: 'python://k8s_crd_resolver/schemata/k8s-1.21.1.json#/definitions/io.k8s.api.core.v1.PodSpec'
                cluster:
                  $ref: 'python://dask_kubernetes/operator/customresources/templates.yaml#/definitions/dask.k8s.api.v1.DaskCluster'
      subresources:
        status: {}
