// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "github.com/dask/dask-kubernetes/v2023/dask_kubernetes/operator/go_client/pkg/apis/kubernetes.dask.org/v1"
	kubernetesdaskorgv1 "github.com/dask/dask-kubernetes/v2023/dask_kubernetes/operator/go_client/pkg/client/applyconfiguration/kubernetes.dask.org/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDaskClusters implements DaskClusterInterface
type FakeDaskClusters struct {
	Fake *FakeKubernetesV1
	ns   string
}

var daskclustersResource = v1.SchemeGroupVersion.WithResource("daskclusters")

var daskclustersKind = v1.SchemeGroupVersion.WithKind("DaskCluster")

// Get takes name of the daskCluster, and returns the corresponding daskCluster object, and an error if there is any.
func (c *FakeDaskClusters) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.DaskCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(daskclustersResource, c.ns, name), &v1.DaskCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.DaskCluster), err
}

// List takes label and field selectors, and returns the list of DaskClusters that match those selectors.
func (c *FakeDaskClusters) List(ctx context.Context, opts metav1.ListOptions) (result *v1.DaskClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(daskclustersResource, daskclustersKind, c.ns, opts), &v1.DaskClusterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.DaskClusterList{ListMeta: obj.(*v1.DaskClusterList).ListMeta}
	for _, item := range obj.(*v1.DaskClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested daskClusters.
func (c *FakeDaskClusters) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(daskclustersResource, c.ns, opts))

}

// Create takes the representation of a daskCluster and creates it.  Returns the server's representation of the daskCluster, and an error, if there is any.
func (c *FakeDaskClusters) Create(ctx context.Context, daskCluster *v1.DaskCluster, opts metav1.CreateOptions) (result *v1.DaskCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(daskclustersResource, c.ns, daskCluster), &v1.DaskCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.DaskCluster), err
}

// Update takes the representation of a daskCluster and updates it. Returns the server's representation of the daskCluster, and an error, if there is any.
func (c *FakeDaskClusters) Update(ctx context.Context, daskCluster *v1.DaskCluster, opts metav1.UpdateOptions) (result *v1.DaskCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(daskclustersResource, c.ns, daskCluster), &v1.DaskCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.DaskCluster), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDaskClusters) UpdateStatus(ctx context.Context, daskCluster *v1.DaskCluster, opts metav1.UpdateOptions) (*v1.DaskCluster, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(daskclustersResource, "status", c.ns, daskCluster), &v1.DaskCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.DaskCluster), err
}

// Delete takes name of the daskCluster and deletes it. Returns an error if one occurs.
func (c *FakeDaskClusters) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(daskclustersResource, c.ns, name, opts), &v1.DaskCluster{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDaskClusters) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(daskclustersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.DaskClusterList{})
	return err
}

// Patch applies the patch and returns the patched daskCluster.
func (c *FakeDaskClusters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.DaskCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(daskclustersResource, c.ns, name, pt, data, subresources...), &v1.DaskCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.DaskCluster), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied daskCluster.
func (c *FakeDaskClusters) Apply(ctx context.Context, daskCluster *kubernetesdaskorgv1.DaskClusterApplyConfiguration, opts metav1.ApplyOptions) (result *v1.DaskCluster, err error) {
	if daskCluster == nil {
		return nil, fmt.Errorf("daskCluster provided to Apply must not be nil")
	}
	data, err := json.Marshal(daskCluster)
	if err != nil {
		return nil, err
	}
	name := daskCluster.Name
	if name == nil {
		return nil, fmt.Errorf("daskCluster.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(daskclustersResource, c.ns, *name, types.ApplyPatchType, data), &v1.DaskCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.DaskCluster), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeDaskClusters) ApplyStatus(ctx context.Context, daskCluster *kubernetesdaskorgv1.DaskClusterApplyConfiguration, opts metav1.ApplyOptions) (result *v1.DaskCluster, err error) {
	if daskCluster == nil {
		return nil, fmt.Errorf("daskCluster provided to Apply must not be nil")
	}
	data, err := json.Marshal(daskCluster)
	if err != nil {
		return nil, err
	}
	name := daskCluster.Name
	if name == nil {
		return nil, fmt.Errorf("daskCluster.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(daskclustersResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1.DaskCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.DaskCluster), err
}
