FROM ghcr.io/dask/dask:latest-py3.10

# Install latest development builds of Dask and Distributed
RUN pip install git+https://github.com/dask/distributed@main
RUN pip install git+https://github.com/dask/dask@main
