FROM ghcr.io/dask/dask:latest

# Install latest dev builds of Dask and Distributed
RUN pip install git+https://github.com/dask/distributed@2022.6.1
RUN pip install git+https://github.com/dask/dask@2022.6.1
